<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22000</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>barcodrod.io</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64;AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <UapAppxPackageBuildMode>SideloadOnly</UapAppxPackageBuildMode>
    <BuildAppxUploadPackageForUap>false</BuildAppxUploadPackageForUap>
    <GenerateTemporaryStoreCertificate>false</GenerateTemporaryStoreCertificate>
    <UserSecretsId>b509cab9-7bac-4a2a-b212-4c9b770155a3</UserSecretsId>
    <AppxPackageDir>D:\barcodrod.io_builds\</AppxPackageDir>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Assets\WindowIcon.ico</ApplicationIcon>
    <AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
    <Configurations>Debug;Release;RELEASE1</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\Segoe Fluent Icons.ttf" />
    <Content Remove="Assets\SmallTile.scale-100.png" />
    <Content Remove="Assets\SmallTile.scale-125.png" />
    <Content Remove="Assets\SmallTile.scale-150.png" />
    <Content Remove="Assets\SmallTile.scale-200.png" />
    <Content Remove="Assets\SmallTile.scale-400.png" />
    <Content Remove="Assets\Square310x310Logo.scale-125.png" />
    <Content Remove="Assets\Square310x310Logo.scale-150.png" />
    <Content Remove="Assets\Square310x310Logo.scale-200.png" />
    <Content Remove="Assets\Square310x310Logo.scale-400.png" />
    <Content Remove="Assets\Square400x400Logo.scale-100.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.scale-125.png" />
    <Content Remove="Assets\Square44x44Logo.scale-200.png" />
    <Content Remove="Assets\Square44x44Logo.scale-400.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-48.png" />
    <Content Remove="Assets\StoreLogo.png" />
    <Content Remove="Assets\StoreLogo.scale-100.scale-100.png" />
    <Content Remove="Assets\StoreLogo.scale-100.scale-125.png" />
    <Content Remove="Assets\StoreLogo.scale-100.scale-150.png" />
    <Content Remove="Assets\StoreLogo.scale-100.scale-200.png" />
    <Content Remove="Assets\StoreLogo.scale-100.scale-400.png" />
    <Content Remove="Assets\StoreLogo.scale-125.png" />
    <Content Remove="Assets\StoreLogo.scale-150.png" />
    <Content Remove="Assets\StoreLogo.scale-200.png" />
    <Content Remove="Assets\StoreLogo.scale-400.png" />
    <Content Remove="Assets\Wide310x150Logo.png" />
    <Content Remove="Assets\Wide310x150Logo.scale-100.png" />
    <Content Remove="Assets\Wide310x150Logo.scale-125.png" />
    <Content Remove="Assets\Wide310x150Logo.scale-150.png" />
    <Content Remove="Assets\Wide310x150Logo.scale-200.png" />
    <Content Remove="Assets\Wide310x150Logo.scale-400.png" />
    <Content Remove="Assets\WindowIcon.png" />
    <Content Remove="Assets\WindowIcon.scale-100.png" />
    <Content Remove="Assets\WindowIcon.scale-125.png" />
    <Content Remove="Assets\WindowIcon.scale-150.png" />
    <Content Remove="Assets\WindowIcon.scale-200.png" />
    <Content Remove="Assets\WindowIcon.scale-400.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\Square310x310Logo.scale-100.png" />
    <None Remove="Assets\Square44x44Logo.scale-100.png" />
    <None Remove="Assets\Square44x44Logo.scale-150.png" />
    <None Remove="Square400x400Logo.scale-100.png" />
    <None Remove="Square400x400Logo.scale-200.png" />
    <None Remove="Square400x400Logo.scale-400.png" />
    <None Remove="Square44x44Logo.scale-100.png" />
    <None Remove="Square44x44Logo.scale-150.png" />
    <None Remove="Square44x44Logo.scale-200.png" />
    <None Remove="Square44x44Logo.scale-400.png" />
  </ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260209005" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WinUIEx" Version="2.9.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.11" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="Contracts\ViewModels\" />
  </ItemGroup>
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>